name: Copy Branch Before Merge

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  copy_branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout target branch
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.base.ref }}

    - name: Create copy branch
      run: |
        git branch copy-${{ github.event.pull_request.base.ref }}
        git checkout copy-${{ github.event.pull_request.base.ref }}
        git push -u origin copy-${{ github.event.pull_request.base.ref }}

    - name: Merge pull request
      run: |
        git checkout ${{ github.event.pull_request.base.ref }}
        git merge ${{ github.event.pull_request.head.ref }}
        git push
